### ISSUE TITLE
samples/basic: POST /problem fails if 'Content-Type' is supplied and is not the last header

### ISSUE THREAD

**Issue by nashneshev** [zlatko-michailov/abc#1]
Repro:

- launch the sample

- from another shell:
`$ curl --data-binary "{\"a\": [ [1, 2], [3, 4] ], \"b\": [5, 6] }" -H "Content-Type: application/json" http://localhost:30301/problem`

- error:
`The Content-Type header was supplied more than once.`

Issue:

The check for "has_valid_content_type" in samples/basic/equations.h has to be moved within the Contebt-Type check above. The sample currently works with the browser, because the browser ends up sending the Content-Type header in lower case.

**Comment by zlatko-michailov** [comment]
@nashneshev  I have to fix this as part of issue #4 . I'm assigning it to myself.

**Comment by zlatko-michailov** [comment]
Fixed in both master and dev.
