### ISSUE TITLE
HTTP server is resetting the connection

### ISSUE THREAD

**Issue by nashneshev** [zlatko-michailov/abc#2]
Repro:

- launch the basic sample

- open up the browser's dev tools (F12), open Networking tab

- Navigate to "http://localhost:30301/resources/index.html"

- Notice that the request status is "net:ERR_CONNECTION_RESET"

- Sometimes the page loads, sometimes it fails and sometimes it shows an error message in the browser console as well

Issue:
Since the server is HTTP/1.1 and it doesn't send back "Connection: close" the client assumes that it will keep the connection open (https://tools.ietf.org/html/rfc2068#section-8.1.2.1).

But the server not only closes the connection, it resets it.

This can be fixed in different ways: 1) Send back HTTP/1.0 from the server - this is closer to how the server currently behaves since it doesn't support keep-alive connections. 2) Add a "Connection: close" header in the response and also attempt to gracefully close the connection. Updating `_basic_socket<Log>::close()` to call `::shutdown(_handle, SHUT_RDWR);` right before `::close(_handle);` seems to do the trick, although ideally the code will be a bit more complicated - drain any remaining data from the client socket after shutdown  and before closing it.

**Comment by zlatko-michailov** [comment]
Fixed in both master and dev.
