### ISSUE TITLE
Make the basic sample easier to run for people new to the library

### ISSUE THREAD

**Issue by nashneshev** [zlatko-michailov/abc#3]
Currently the basic sample just starts without printing out anything to the console and it is up to the client to figure out that they need to launch a browser and point it to a specific URL and that the sample has to be started from the root of the project.

Consider:
- Printing a message that the server is listening on port 30301 and that the user should open up a browser and naviagate to http://localhost:30301/resources/index.html
- Fixing the sample's main.cpp so that the folder from which the sample was executed wouldn't matter and instead it registers root_dir relative to the executable's location

**Comment by zlatko-michailov** [comment]
Fixed in both master and dev.
