### ISSUE TITLE
HTTP server only accepts requests to localhost / 127.0.0.1 interface

### ISSUE THREAD

**Issue by nashneshev** [zlatko-michailov/abc#5]
Repro (on Ubuntu 20.04):
- Launch the basic sample, open up a browser on the same machine, navigate to `http://localhost/resources/index.html` - works
- Open up a browser on the local machine, navigate to `http://<machine's IP>/resources.index.html` - connection refused

Analysis - it seems like the listener binds to the first interface it can resolve (the loop in `_basic_socket<Log>::tie`) and that one likely is 127.0.0.1. This should ideally be configurable, or it should bind to 0.0.0.0, so that clients outside of the machine can connect to the HTTP server.

**Comment by zlatko-michailov** [comment]
Resolved in commit b22a0b4a9324824b2b46a94082e4ae1ea9134094.

Merged into master and dev.
