### ISSUE TITLE
Make the project buildable for 32-bit systems

### ISSUE THREAD

**Issue by zlatko-michailov** [zlatko-michailov/abc#9]
This issue is open for grabs.

There should be either a shell script or a makefile target that would compile 32-bit binaries (preferably for the current platform.) It shouldn't be executed on every make. Only when needed.

**Comment by zlatko-michailov** [comment]
@nashneshev I'll appreciate your help with this one, if you have time.

**Comment by nashneshev** [comment]
What will be the target scenario? Is it to ensure that nothing is broken on 32 bit systems when working on a 64 bit one? In that case the script / target should run the tests as well.

**Comment by zlatko-michailov** [comment]
Ideally, yes - if we can build and test both 64- an 32-bit on each platform, that would be perfect. (On 32-bit platforms, we may end up doing the same thing twice, but I guess that's OK. We can figure how to optimize later.)

However, the above doesn't seem possible. At least I couldn't figure it in my brief investigation. The compiler options are specific to the platform. In particular, the -m32 option applies to x86_x64, but not to arm. That's why I am not very optimistic about the feasibility of the above.

Therefore, I would be fine with simply building both 32- and 64-bit for x86_x64 without running any tests.

**Comment by nashneshev** [comment]
OK, you can assign it to me, but I'll need some time to investigate.

**Comment by zlatko-michailov** [comment]
There is no urgency on this issue.

I am leaving it unassigned, i.e. it is up for grabs. If you have time and desire some day, you'll be welcome to pick it up. Otherwise, I will do something about it when I'm done with everything else.

**Comment by zlatko-michailov** [comment]
Done.
